### ISSUE TITLE
Broken vignette plots

### ISSUE THREAD

**Issue by dashaub** [eddelbuettel/gcbd#2]
Hi Dirk, it looks like the lattice plots on page 9 of the [vignette](https://cran.r-project.org/web/packages/gcbd/vignettes/gcbd.pdf) broke.

**Comment by eddelbuettel** [comment]
Indeed, noted.

**Comment by jay-sf** [comment]
Still broken in 2022 in vignette shipped with freshly installed package gcbd 0.2.6. Cheers

**Comment by eddelbuettel** [comment]
If you add `library(lattice)` before calling `figure_Lattice()` then Figure 2 reproduces just fine:

![image](https://user-images.githubusercontent.com/673121/154844836-0518ac5b-ee4a-49eb-bbd4-c089988d2cfe.png)

Ditto for Figure 3 via `figure_LogLogLattice()`:

![image](https://user-images.githubusercontent.com/673121/154845010-15e326d6-19dd-429b-bbab-99a4a947d907.png)

The culprit is the no longer (automagically ?) exported function `panel.superpose()` which, once added to `NAMESPACE` makes things work again.   I'll add it.
